project:
  seed: 42
  paths:
    data_raw: "data/raw"
    data_interim: "data/interim"
    data_processed: "data/processed"
    models_dir: "models"
    reports_tables: "reports/tables"
    reports_figures: "reports/figures"
    logging_config: "configs/logging.yaml"

data_prep:
  date_column: "data"
  family_column: "familia"
  product_column: "produto"
  target_column: "quantidade"
  frequency: "M"        # mensal (fim do mês)
  test_size_months: 6
  synthetic:
    enabled: false
  lags: [1, 2, 3, 6, 12]
  rolling_windows: [3, 6]

forecast:
  horizon_months: 6
  folds: 3
  models:
    moving_average:
      enabled: true
      window: [3]             # você pode testar [3, 6]
    ses:
      enabled: true
      alpha: [0.3]            # ou deixe vazio e otimize no código
      optimized: [false]
    holt:
      enabled: true
      alpha: [0.3]
      beta: [0.1]
      optimized: [false]
    arima:
      enabled: false
    svr:
      enabled: true
      kernel: ["rbf"]
      C: [1.0, 10.0]
      gamma: ["scale"]
    random_forest:
      enabled: true
      n_estimators: [200]
      max_depth: [6, 10]
      min_samples_leaf: [2, 5]
    xgboost:
      enabled: true
      n_estimators: [300]
      max_depth: [4, 6]
      learning_rate: [0.05]
      subsample: [0.8]
      colsample_bytree: [0.8]

# optimization:
  initial_inventory: { "A": 0, "B": 0 }
  cost_parameters:
    default:
      production: 1.0
      inventory: 0.2
      backlog: 3.0
  capacity_per_period:  # por mês (YYYY-MM) ou "default"
    default: 10000

# rrp:
  productivity_units_per_hour: { "A": 50, "B": 40 }
  capacity_hours_per_period:
    default: 250

# disaggregation:
  proportions:
    A:
      "A_prod_1": 0.5
      "A_prod_2": 0.3
      "A_prod_3": 0.2
    B:
      "B_prod_1": 0.4
      "B_prod_2": 0.35
      "B_prod_3": 0.25
