version: 1
formatters:
  simple:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: reports/tables/tcc.log
loggers:
  root:
    level: INFO
    handlers: [console, file]
